Numpy is a fundamental library for scientific computing in Python.
It provides support for arrays and matrices along with collection of mathematical fn to operate on these data structure.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

# create array using numpy
# create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)   # single dimension with 5 elements

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape((1, 5))    # 2D array, 1row 5column


array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
arr2.shape  # 2D array

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# identity matrix :: diagonal element 1 hona chahiye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("No of dimensions:\n", arr.ndim)
print("Size:\n", arr.size)
print("Data Type:\n", arr.dtype)
print("Item size(bytes):\n", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
No of dimensions:
 2
Size:
 6
Data Type:
 int64
Item size(bytes):
 8


In [18]:
# Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element wise addition
print("Addition:", arr1+arr2)

# Element wise subtraction
print("Subtraction:", arr1-arr2)

# Element wise multiplication
print("Multiplication:", arr1*arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]


In [20]:
# Logical Operation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[data > 5]

array([ 6,  7,  8,  9, 10])

In [23]:
# Logical Operation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])